### ISSUE TITLE
Use the "latest version" link to download Ubooquity

### ISSUE THREAD

**Issue by vaemendis** [hurricanehrndz/ubooquity#4]
Hello,

why not use the link provided by the Ubooquity website that always delivers the latest version ?
Line 42 of your script would be something like:

```
RUN wget -O ubooquity.zip http://vaemendis.net/ubooquity/service/download.php && unzip ubooquity.zip -d UbooquityInstall
```

This way, no need to update the script each time a new version of Ubooquity is released.

**Comment by hurricanehrndz** [comment]
Okay, this will get reworked.

**Comment by hurricanehrndz** [comment]
Done! Please see the following:
https://github.com/hurricanehrndz/docker-containers/blob/master/ubooquity/README.md

**Comment by vaemendis** [comment]
Nice !
