### ISSUE TITLE
Ubooquity 1.10.1 Now Requires Java 8

### ISSUE THREAD

**Issue by DaveHavok** [hurricanehrndz/ubooquity#5]
Docker needs to be updated to install Java 8 instead of Java 7, otherwise it fails to run.

**Comment by hurricanehrndz** [comment]
Thanks. I will be updating today.

**Comment by hurricanehrndz** [comment]
Okay I have resolved the issue, but I can not update the image until Docker fixes an issue on their build server: https://github.com/docker-library/official-images/pull/1537#issuecomment-196652045
Here is the image
https://github.com/hurricanehrndz/docker-containers/tree/master/ubooquity

**Comment by DaveHavok** [comment]
Thanks for much for updating this Docker. Definitely appreciate it and I hope things are going well.
