### ISSUE TITLE
WebUI Link In UnRAID Dashboard Still Points To Port 8085 Instead Of 2202

### ISSUE THREAD

**Issue by DaveHavok** [hurricanehrndz/ubooquity#6]
The recent Docker plugin update to Ubooquity appears to have changed the port to 2202, but the WebUI link still points to 8085, so the user can't access the the Admin panel unless they correct the Port number in the URL link itself.

**Comment by DaveHavok** [comment]
This issue is correctable by clicking on Edit to bring up the Docker details. Then clicking on the Advanced View on the far right. 

Down in the Additional Fields section is where you can change the WebUI port.

**Comment by hurricanehrndz** [comment]
On May 18, 2016 11:36 PM, "DaveHavok" <notifications@github.com> wrote:
>
> The recent Docker plugin update to Ubooquity appears to have changed the
port to 2202, but the WebUI link still points to 8085, so the user can't
access the the Admin panel unless they correct the Port number in the URL
link itself.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
<https://github.com/hurricanehrndz/ubooquity/issues/6>

**Comment by hurricanehrndz** [comment]
This has been addressed. Please don't open any more issue in this project as it is getting deleted. Either open them in container-templates for template issues or docker-containers. Thank you.
