### ISSUE TITLE
Docker Does Not Auto Update

### ISSUE THREAD

**Issue by DaveHavok** [hurricanehrndz/ubooquity#7]
- Ubooquity Docker shows the notification that 1.10.1 is available for download

- Stopping / Restarting the Docker does not push the auto update function

- Reinstalling the Docker does not seem to correct this behavior either

- Manually replacing the JAR file does not seem to work either

Log Dump:
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - #############################
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - # Starting Ubooquity #
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - #############################
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - Java version: 1.8.0_77
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - Java vendor: Oracle Corporation
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - Max heap size available: 455 MB
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - OS name: Linux
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - OS version: 4.1.18-unRAID
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - OS architecture: amd64
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - Loading local version info
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - Ubooquity 1.10.0 built on 2016-05-08 at 19:51
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - Creating application folders
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/Charis SIL.css to /config/fonts/Charis SIL.css
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/CharisSIL-B.woff to /config/fonts/CharisSIL-B.woff
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/CharisSIL-BI.woff to /config/fonts/CharisSIL-BI.woff
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/CharisSIL-I.woff to /config/fonts/CharisSIL-I.woff
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/CharisSIL-R.woff to /config/fonts/CharisSIL-R.woff
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/Fira Sans.css to /config/fonts/Fira Sans.css
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/FiraSans-Bold.woff to /config/fonts/FiraSans-Bold.woff
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/FiraSans-BoldItalic.woff to /config/fonts/FiraSans-BoldItalic.woff
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/FiraSans-Italic.woff to /config/fonts/FiraSans-Italic.woff
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/FiraSans-Regular.woff to /config/fonts/FiraSans-Regular.woff
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/texgyrepagella-bold.woff to /config/fonts/texgyrepagella-bold.woff
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/texgyrepagella-bolditalic.woff to /config/fonts/texgyrepagella-bolditalic.woff
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/texgyrepagella-italic.woff to /config/fonts/texgyrepagella-italic.woff
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/texgyrepagella-regular.woff to /config/fonts/texgyrepagella-regular.woff
20160518 19:34:08 [main] ERROR com.ubooquity.f.a - Could not extract file: fonts/Tex Gyre Pagella.css to /config/fonts/Tex Gyre Pagella.css
20160518 19:34:08 [main] INFO com.ubooquity.Ubooquity - Loading preferences
20160518 19:34:08 [main] INFO com.ubooquity.c - Starting internal server...
20160518 19:34:08 [Scanner thread] INFO com.ubooquity.data.feeder.a - Scanning books directories
20160518 19:34:08 [Scanner thread] INFO com.ubooquity.data.feeder.a - Finished scanning books directories, populating folders content cache
20160518 19:34:08 [Scanner thread] INFO com.ubooquity.data.feeder.a - Books folder content cache populated
20160518 19:34:08 [Scanner thread] INFO com.ubooquity.data.feeder.a - Scanning comics directories
20160518 19:34:08 [main] INFO com.ubooquity.c - Reverse proxy prefix is not activated
20160518 19:34:08 [main] INFO com.ubooquity.c - Internal server started. Listening on port 2202

**Comment by hurricanehrndz** [comment]
https://github.com/hurricanehrndz/docker-containers/blob/master/ubooquity/README.md#unraid-automatic-upgrades

I have yet to enable my build server, but for now you can update from the command line or via cron on a schedule you deem fit.

For now I will trigger a build, but that being said the containers will be automatically build on new ubooquity releases in the near future. 

Thanks.

**Comment by hurricanehrndz** [comment]
Manual one time upgrades 
https://github.com/hurricanehrndz/docker-containers/blob/master/ubooquity/README.md#upgrading
